name: Verify

on:
  pull_request:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    name: Java ${{ matrix.java }} compile and run tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt-hotspot'
      - name: Compile with Java ${{ matrix.java }}
        run: mvn test --no-transfer-progress
